esphome:
  name: raspiaudio-muse-proto
  friendly_name: RaspiAudio Muse Proto
  min_version: 2024.9.0
  name_add_mac_suffix: true

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:

captive_portal:
